package pl.befit.projektnaio.ListOfGyms;

public enum SortingPredicate {
    LOCATION_DECREASING,LOCATION_INCREASING,DATE_DECREASING,DATE_INCREASING,NOTE_DECREASING,NOTE_INCREASING,
    TICKETPRICE_DECREASING,TICKETPRICE_INCREASING, NONE
}
